### ISSUE TITLE
Cannot add Prism.Validation to my Prism Xamarin project

### ISSUE THREAD

**Issue by weitzhandler** [mfe-/Prism.Validation#10]
Hi,

I have a Prism Xamrin poroject targeting Android, iOS and UWP.
I'm trying to add a reference to this package in the portable project, and I get the following error:
>install-package : Could not install package 'System.ComponentModel.Annotations 4.3.0'. You are trying to install this package into a project that 
targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible 
with that framework. For more information, contact the package author.

I tried following the first instruction from [here](https://github.com/mfe-/Prism.Validation#use):
>Use in your PCL Profile ```Profile7``` (Set in your .csproj```<TargetFrameworkProfile>Profile7</TargetFrameworkProfile>```)

But haven't found the `TargetFrameworkProfile` property in the portable project's *csproj* file.

**Comment by weitzhandler** [comment]
Desn't matter, but what might matter is I'm on VS 2017 RC .NET Framework 4.6.2.
When you're creating a new Prism project in VS 2015 targeting Droid, iOS and UWP, does it work?

**Comment by mfe-** [comment]
The quoted instructions are related to the Prism.Validation 1.0.0.0. I'm sorry that I didn't explain that better in the [Readme.md](https://github.com/mfe-/Prism.Validation/blob/45d254082ab3fb9c42ecc6e7c13a26f476930390/README.md). I updated it with the last commit.

> When you're creating a new Prism project in VS 2015 targeting Droid, iOS and UWP, does it work?

I haven't used or tested the Prism.Validation for Xamarin Forms. But you are able to convert your Xamarin.Forms App project from PCL to .NetStandard with this guide https://oren.codes/2016/07/09/using-xamarin-forms-with-net-standard/.

By setting `"imports": "portable45-net45+win8+wp8+wpa81"` in the project.json you are able to reference the required PCL dependencies like Prism.Core.

Since .NetStandard provides System.ComponentModel.Annotations you should be able to install Prism.Validation into your XF project.

I hope this helps!

Unfortunately I can't create any XF Projects since my last Xamarin update broke my Visual Studio. I'll fix that soon.

**Comment by weitzhandler** [comment]
The problem is that Prism won't support .NET standard [until version 2.0 is released](https://github.com/PrismLibrary/Prism/issues/683#issuecomment-263600123) :broken_heart:

**Comment by mfe-** [comment]
@weitzhandler Using the latest version of [Prism](https://www.nuget.org/packages/Prism.Core/7.0.0.396) and [Prism.Validation](https://www.nuget.org/packages/Prism.Validation/1.2.0) fixes this issue (as they are targeting .NETStandard)
